---
title: "06 Using a mobile device to capture data in the field using an e-form"
author: "Derrick Theophille"
date: last-modified
date-format: "DD MMMM YYYY"

format: 
  html:
    toc: true
    number-sections: true
    fig_caption: false

execute: 
  echo: true
  message: false
  warning: false
  
knitr: 
  opts_chunk: 
    comment: false
    collapse: true
---

```{r}
#| label: sources
#| echo: false

# some-sources

# 

```

As you may have noticed, electronic data collection can be used in the work place as well as in the field. We will focus on field data collection in this section.

# Before going on the field

It is good practice to be prepared before going into the field to collect data.

- Ensure that the mobile device is fully charged. Depending on device power consumption, you may opt to carry replacement batteries or back-up power sources, based on the device. Or you may choose to carry a second, charged, device.
- Make sure the latest version of the e-form is loaded on to the device. It is also a good idea to test the e-form, while connected to the internet, just to confirm that the e-form is properly loaded.
- If you require additional accessories, supplies, and tools which support your data collection work or your device specifically, make sure those are kept along with your device.
- If the device uses a case and screen protector for added protection, install those now.

# While on the field

- Keep the device and accessories safe and secure, especially when when not in use.
- Tablets should only be used for data collection activities
- Never let the device leave your sight. Avoid lending the device to other people.

# Return from field

- Make sure device is cleaned from dirt/soil, liquid, etc
- Make sure device is put to charge.
- Make sure device is connected to internet and browser is open for the submission of records.
- Designate a safe place to keep and securely store the devices when not in use. For example in a locked cabinet.
- Proper care and maintenance should be adhered to at all times.


# Recap and next steps

Let's recap. So far you have learned: 

- The importance of data
- The difference between paper and electronic data collection methods
- The basics of designing a survey and developing a good questionnaire
- What is KoboToolbox and been introduced to its features
- How to create a KoboToolbox account, create a basic e-questionnaire and deploy it
- How to use a mobile device for data collection in the field

Now what?




